language: go

go: "1.14"

install:
- wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
- sudo unzip ninja-linux.zip
- mv ninja $GOPATH/bin

script:
- cd $GOPATH/src/github.com/vladShadow/Architecture-LAB22/build
- sudo chmod +x my-bood-initial
- ./my-bood-initial
- mv -f my-build.bood build.bood # initial build.bood is needed to show later that build can not be executed for the same files twice
- ./out/bin/bood # will show that only tests were executed
- cat out/bin/test.txt # to show that test.txt was created indeed
- ./out/bin/bood # to show that neither build nor tests were executed
- cd $GOPATH/src/github.com/vladShadow/Architecture-LAB22/examples # to demonstrate examples as well
- ../build/out/bin/bood