language: go

go: "1.14"

install:
- wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
- sudo unzip ninja-linux.zip
- mv ninja $GOPATH/bin

script:
- cd $GOPATH/src/github.com/vladShadow/Architecture-LAB22/build
- ./my-bood-initial
- /out/bin/bood